name: Deploy Lambda

on:
  push:
    branches: [main]
    paths:
      - 'producer/terraform/**'
      - '.github/workflows/deploy_lambda.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Descargar lambda.zip desde artifacts
        uses: actions/download-artifact@v4
        with:
          name: lambda-package
          path: producer/terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: producer/terraform
        run: terraform init

      - name: Importar Lambda si ya existe
        working-directory: producer/terraform
        run: |
          LAMBDA_EXISTS=$(aws lambda get-function --function-name csv_corrector_lambda --region us-east-1 --query 'Configuration.FunctionName' --output text 2>/dev/null || echo "NONE")
          if [ "$LAMBDA_EXISTS" != "NONE" ]; then
            terraform import aws_lambda_function.csv_corrector csv_corrector_lambda || true
          fi

      - name: Terraform Apply
        working-directory: producer/terraform
        run: terraform apply -auto-approve
